# -*- coding: utf-8 -*-
"""Code_no_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Xx3UvQ8rUm5kjBdX4w7sV7TBdWcamp1o
"""

def min_cf(cf1, cf2):
    return min(cf1, cf2)

def deteksi_hama_cf(gejala_input):
    # Daftar gejala yang benar-benar terjadi (bernilai True)
    gejala = {g: v for g, v in gejala_input.items() if v}

    hasil = {}

    # Aturan 1: daun menguning ∧ tanaman layu → ulat tanah (CF 0.8)
    if gejala_input["daun_menguning"] and gejala_input["tanaman_layu"]:
        cf = min_cf(1.0, 1.0) * 0.8
        hasil["Ulat Tanah"] = cf

    # Aturan 2: bercak hitam ∧ daun menguning → jamur (CF 0.7)
    if gejala_input["bercak_hitam"] and gejala_input["daun_menguning"]:
        cf = min_cf(1.0, 1.0) * 0.7
        hasil["Jamur"] = cf

    # Aturan 3: daun berlubang → ulat daun (CF 0.6)
    if gejala_input["daun_berlubang"]:
        cf = 1.0 * 0.6
        hasil["Ulat Daun"] = cf

    # Aturan 4: daun berlubang ∧ bercak hitam → kumbang daun (CF 0.75)
    if gejala_input["daun_berlubang"] and gejala_input["bercak_hitam"]:
        cf = min_cf(1.0, 1.0) * 0.75
        hasil["Kumbang Daun"] = cf

    # Menentukan hasil dengan CF tertinggi
    if hasil:
        hama_terdeteksi = max(hasil, key=hasil.get)
        return hama_terdeteksi, hasil[hama_terdeteksi]
    else:
        return "Tidak diketahui", 0.0

# Contoh input gejala
gejala_input = {
    "daun_menguning": True,
    "bercak_hitam": False,
    "daun_berlubang": False,
    "tanaman_layu": True
}

hasil, cf = deteksi_hama_cf(gejala_input)
print(f"Jenis hama: {hasil} (CF: {cf})")